name = "honeybadger"
main = "src/index.ts"
compatibility_date = "2023-03-08"

[vars]
# Required secrets:
# - SLACK_TOKEN
# - SLACK_CHANNEL
# Sample .dev.vars for development
# SLACK_TOKEN=<token-value>
# SLACK_CHANNEL=<channel-name-or-id>
